#ifndef CPDCONSTANTS_H
#define CPDCONSTANTS_H

#define EPS 0.000000001
#define PARTICLE_RADIUS 1.0
#define PARTICLE_MASS 1.0
#define PARTICLE_PROXIMITY 0.2
#define STATIC_FRICTION 0.2
#define DYNAMIC_FRICTION 0.1
#define STOP_THRESHOLD 0.001
#define PARTICLE_DAMPING 0.05

#define CONSTRAINT_STIFFNESS 0.5
#define CONSTRAINT_STIFFNESS_DISTANCE 0.5
#define CONSTRAINT_STIFFNESS_DIHEDRAL 0.0001
#define COLLISION_SOLVER_ITERATION 5
#define CONSTRAINT_SOLVER_ITERATION 3
#define PRE_STABLIZE_ITERATION 2
#define OVER_RELAXATION 0.2

#define TIMESTEP 0.01

#endif // !CPDCONSTANTS_H